# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentcfg < Formula
  desc "Scriptable CLI to sync skills, hooks, and instruction files across local AI coding agent configurations."
  homepage "https://github.com/jorgenosberg/agentcfg"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/agentcfg_darwin_amd64.tar.gz"
      sha256 "81a2b7655c64c6f9b9e3dc1220a4ad41a62b84b031e3a1b237dec344ca8cb54c"

      define_method(:install) do
        bin.install "agentcfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/agentcfg_darwin_arm64.tar.gz"
      sha256 "aae4bbc876ace7d4e89a42232bcf0afa93358ff28a5dd2c6122949920947c831"

      define_method(:install) do
        bin.install "agentcfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/agentcfg_linux_amd64.tar.gz"
      sha256 "fea523da119d82a92ba86d75e67b87d2002ba814522ac46b9f2a3976b955b846"
      define_method(:install) do
        bin.install "agentcfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/agentcfg_linux_arm64.tar.gz"
      sha256 "1ef693762c0c965e5d76bec992ea17955a24b2b055b858c72bc553e8a291a8a5"
      define_method(:install) do
        bin.install "agentcfg"
      end
    end
  end

  test do
    system "#{bin}/agentcfg", "--version"
  end
end
