# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Agentcfg < Formula
  desc "Scriptable CLI to sync skills, hooks, and instruction files across local AI coding agent configurations."
  homepage "https://github.com/jorgenosberg/agentcfg"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/agentcfg_darwin_amd64.tar.gz"
      sha256 "569142b60651868b109a4b38b337962464b05f944e1c660c9b2c0f70ca89200a"

      define_method(:install) do
        bin.install "agentcfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/agentcfg_darwin_arm64.tar.gz"
      sha256 "721ddba96c7e64f7fe7a1244a724d37a54500f89b3ab410b6d0e8019a7f8676a"

      define_method(:install) do
        bin.install "agentcfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/agentcfg_linux_amd64.tar.gz"
      sha256 "6e5418ee4ecf15fcf0891f8820155444a993b36bd40d28e9821ff45d445baf57"
      define_method(:install) do
        bin.install "agentcfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/agentcfg_linux_arm64.tar.gz"
      sha256 "17084de707dd7052d1f29e812b711977a2fe67f8117fbfcf28200d6a32a4379c"
      define_method(:install) do
        bin.install "agentcfg"
      end
    end
  end

  test do
    system "#{bin}/agentcfg", "--version"
  end
end
