# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagentcfg < Formula
  desc "Interactive TUI for managing AI coding agent configurations (lazygit-style)."
  homepage "https://github.com/jorgenosberg/agentcfg"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/lazyagentcfg_darwin_amd64.tar.gz"
      sha256 "97f722493cc042d9718dd70a32d830ca72b9f819fde8fdf7e5e45b71f2419629"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/lazyagentcfg_darwin_arm64.tar.gz"
      sha256 "ad5bd3bd64c6493d280ecbea06158d98391d2940e5cad7ac217d9a49a090339f"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/lazyagentcfg_linux_amd64.tar.gz"
      sha256 "f072f603087f6398e22fbe47e4172834ac5818e7fddecc5ef6cf4c2480513ad6"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.1/lazyagentcfg_linux_arm64.tar.gz"
      sha256 "9cbbdcc6f7e565943b04ae601788c6bb8b870a795ee8e45e2fd4c1f4ebcf248b"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  test do
    system "#{bin}/lazyagentcfg", "--version"
  end
end
