# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagentcfg < Formula
  desc "Interactive TUI for managing AI coding agent configurations (lazygit-style)."
  homepage "https://github.com/jorgenosberg/agentcfg"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/lazyagentcfg_darwin_amd64.tar.gz"
      sha256 "fc0f5275d1530e87ef5b5877a464794f1701b9638a2e445161f9d7bb1e888e74"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/lazyagentcfg_darwin_arm64.tar.gz"
      sha256 "39717152299c878c7fd4a111377f25fc7a3355927aa913b2dba58ce18b8aa952"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/lazyagentcfg_linux_amd64.tar.gz"
      sha256 "6e5c50fea1e92bda6663453e05d3feea8c95f2952482e5140ea851c21004c054"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.1.0/lazyagentcfg_linux_arm64.tar.gz"
      sha256 "66ade7eef7246e58aeff8218449649ed91383c4fef7d8d9ffd19b3918a9b176a"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  test do
    system "#{bin}/lazyagentcfg", "--version"
  end
end
