# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyagentcfg < Formula
  desc "Interactive TUI for managing AI coding agent configurations (lazygit-style)."
  homepage "https://github.com/jorgenosberg/agentcfg"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.2.0/lazyagentcfg_darwin_amd64.tar.gz"
      sha256 "454babc66a7462c383a8648b7b4618d3daa7c69642d0caba887eb684991af701"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.2.0/lazyagentcfg_darwin_arm64.tar.gz"
      sha256 "6e769dfc6d00f28c8fb29394b113c5fa9745198d123e3c2feede033373ea4256"

      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.2.0/lazyagentcfg_linux_amd64.tar.gz"
      sha256 "40ec520b2e8efc9a924078c8f8b9bbe4bdb9555f422fbe1b553543dabbfc1cef"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jorgenosberg/agentcfg/releases/download/v0.2.0/lazyagentcfg_linux_arm64.tar.gz"
      sha256 "478c772e9a73c9562de6193a6c228778b7bc047401703310b0d724f6029a58ac"
      define_method(:install) do
        bin.install "lazyagentcfg"
      end
    end
  end

  test do
    system "#{bin}/lazyagentcfg", "--version"
  end
end
